### ISSUE TITLE
Runtime exception when compiling after upgrading Slang version

### ISSUE THREAD

**Issue by il1aster** [shader-slang/slang#3759]
Hello,

I have a Vulkan/CUDA application that follows the shader-toy example code to compile slang modules at runtime through the Slang API, but after upgrading Slang from v2023.1.1 to any newer release I get a 'Slang::InternalError' exception when attempting to generate the SPIR-V code. Building Slang from source and running the shader-toy example reproduces the issue for me. I am using a GTX 2070 Super and have gotten the same results with Linux Mint and a fresh Arch install (current).

Output from slang-test: `100% of tests passed (1568/1568), 1118 tests ignored`. 

Backtrace from the shader-toy example compiled with debug mode (x64):
```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, 
    no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff4cab393 in __pthread_kill_internal (signo=6, threadid=<optimized out>)
    at pthread_kill.c:78
#2  0x00007ffff4c5a6c8 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff4c424b8 in __GI_abort () at abort.c:79
#4  0x00007ffff449ca6f in __gnu_cxx::__verbose_terminate_handler ()
    at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#5  0x00007ffff44b011c in __cxxabiv1::__terminate (handler=<optimized out>)
    at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#6  0x00007ffff44b0189 in std::terminate ()
    at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#7  0x00007ffff44b043f in __cxxabiv1::__cxa_rethrow ()
    at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_throw.cc:136
#8  0x00007ffff7548aad in Slang::lowerDecl (context=0x7fffffffc940, decl=0x55555b3e24b8)
    at ../../../source/slang/slang-lower-to-ir.cpp:9891
#9  0x00007ffff7548ed8 in Slang::ensureDecl (context=0x7fffffffd2e0, decl=0x55555b3e24b8)
    at ../../../source/slang/slang-lower-to-ir.cpp:9940
#10 0x00007ffff75497e3 in Slang::emitDeclRef (context=0x7fffffffd2e0, decl=0x55555b3e24b8, 
    subst=0x0, type=0x55555bf654d8) at ../../../source/slang/slang-lower-to-ir.cpp:10059
#11 0x00007ffff7549edf in Slang::emitDeclRef (context=0x7fffffffd2e0, declRef=..., 
    type=0x55555bf654d8) at ../../../source/slang/slang-lower-to-ir.cpp:10228
#12 0x00007ffff7551a59 in Slang::ValLoweringVisitor::visitDeclaredSubtypeWitness (
    this=0x7fffffffcd00, val=0x55555b3f2df0) at ../../../source/slang/slang-lower-to-ir.cpp:1648
#13 0x00007ffff758b290 in Slang::ValVisitor<Slang::ValLoweringVisitor, Slang::LoweredValInfo, Slang::LoweredValInfo>::dispatch_DeclaredSubtypeWitness (this=0x7fffffffcd00, obj=0x55555b3f2df0, 
    extra=0x7fffffffccb0) at ../../../source/slang/slang-visitor.h:298
#14 0x00007ffff6f21bd3 in Slang::Val::accept (this=0x55555b3f2df0, visitor=0x7fffffffcd00, 
    extra=0x7fffffffccb0) at ../../../source/slang/slang-ast-reflect.cpp:81
#15 0x00007ffff75698dc in Slang::ValVisitor<Slang::ValLoweringVisitor, Slang::LoweredValInfo, Slang::LoweredValInfo>::dispatch (this=0x7fffffffcd00, val=0x55555b3f2df0)
    at ../../../source/slang/slang-visitor.h:294
#16 0x00007ffff754231d in Slang::lowerVal (context=0x7fffffffd2e0, val=0x55555b3f2df0)
    at ../../../source/slang/slang-lower-to-ir.cpp:2097
#17 0x00007ffff75400b4 in Slang::lowerSimpleVal (context=0x7fffffffd2e0, val=0x55555b3f2df0)
    at ../../../source/slang/slang-lower-to-ir.cpp:1259
#18 0x00007ffff7549958 in Slang::emitDeclRef (context=0x7fffffffd2e0, decl=0x55555b3e2150, 
    subst=0x55555b4a3b70, type=0x55555bf64f60) at ../../../source/slang/slang-lower-to-ir.cpp:10097
#19 0x00007ffff7549edf in Slang::emitDeclRef (context=0x7fffffffd2e0, declRef=..., 
    type=0x55555bf64f60) at ../../../source/slang/slang-lower-to-ir.cpp:10228
#20 0x00007ffff754a809 in Slang::lowerProgramEntryPointToIR (context=0x7fffffffd2e0, 
    entryPoint=0x55555b5e8d90, specializationInfo=0x55555b3e0840)
    at ../../../source/slang/slang-lower-to-ir.cpp:10338
#21 0x00007ffff75679ef in Slang::SpecializedComponentTypeIRGenContext::visitEntryPoint (
    this=0x7fffffffd550, entryPoint=0x55555b5e8d90, specializationInfo=0x55555b3e0840)
    at ../../../source/slang/slang-lower-to-ir.cpp:10753
#22 0x00007ffff70f9294 in Slang::EntryPoint::acceptVisitor (this=0x55555b5e8d90, 
    visitor=0x7fffffffd550, specializationInfo=0x55555b3e0840)
    at ../../../source/slang/slang-compiler.cpp:225
#23 0x00007ffff77ba4fd in Slang::ComponentTypeVisitor::visitChildren (this=0x7fffffffd550, 
    composite=0x55555b3e0210, specializationInfo=0x55555b8fd870)
    at ../../../source/slang/slang.cpp:5139
#24 0x00007ffff7567e71 in Slang::SpecializedComponentTypeIRGenContext::visitComposite (
    this=0x7fffffffd550, composite=0x55555b3e0210, specializationInfo=0x55555b8fd870)
    at ../../../source/slang/slang-lower-to-ir.cpp:10819
#25 0x00007ffff77b928e in Slang::CompositeComponentType::acceptVisitor (this=0x55555b3e0210, 
    visitor=0x7fffffffd550, specializationInfo=0x55555b8fd870)
    at ../../../source/slang/slang.cpp:4691
#26 0x00007ffff77ba605 in Slang::ComponentTypeVisitor::visitChildren (this=0x7fffffffd550, 
    specialized=0x55555b672620) at ../../../source/slang/slang.cpp:5145
#27 0x00007ffff7567e97 in Slang::SpecializedComponentTypeIRGenContext::visitSpecialized (
    this=0x7fffffffd550, specialized=0x55555b672620)
    at ../../../source/slang/slang-lower-to-ir.cpp:10824
#28 0x00007ffff77ba109 in Slang::SpecializedComponentType::acceptVisitor (this=0x55555b672620, 
    visitor=0x7fffffffd550, specializationInfo=0x0) at ../../../source/slang/slang.cpp:5084
#29 0x00007ffff7567923 in Slang::SpecializedComponentTypeIRGenContext::process (this=0x7fffffffd550, 
    componentType=0x55555b672620, inSink=0x7fffffffd820)
    at ../../../source/slang/slang-lower-to-ir.cpp:10741
#30 0x00007ffff754be6b in Slang::generateIRForSpecializedComponentType (
    componentType=0x55555b672620, sink=0x7fffffffd820)
    at ../../../source/slang/slang-lower-to-ir.cpp:10840
#31 0x00007ffff77b99b0 in Slang::SpecializedComponentType::SpecializedComponentType (
    this=0x55555b672620, base=0x55555b3e0210, specializationInfo=0x55555b8fd870, 
    specializationArgs=..., sink=0x7fffffffd820) at ../../../source/slang/slang.cpp:4869
#32 0x00007ffff77b7b9a in Slang::ComponentType::specialize (this=0x55555b3e0210, 
    inSpecializationArgs=0x55555b6c5b70, specializationArgCount=1, sink=0x7fffffffd820)
    at ../../../source/slang/slang.cpp:4322
#33 0x00007ffff77b7e6c in Slang::ComponentType::specialize (this=0x55555b3e0210, 
    specializationArgs=0x55555b67df90, specializationArgCount=1, 
    outSpecializedComponentType=0x7fffffffd930, outDiagnostics=0x7fffffffd910)
    at ../../../source/slang/slang.cpp:4368
#34 0x0000555555558aef in ShaderToyApp::loadShaderProgram (this=0x7fffffffdd20, 
    device=0x55555ab5f2b0, outShaderProgram=...) at ../../../examples/shader-toy/main.cpp:242
#35 0x000055555555941b in ShaderToyApp::initialize (this=0x7fffffffdd20)
    at ../../../examples/shader-toy/main.cpp:301
#36 0x000055555555a61d in innerMain<ShaderToyApp> ()
    at ../../../examples/example-base/example-base.h:88
#37 0x000055555555749b in main () at ../../../examples/shader-toy/main.cpp:391
```

Thank you in advance for looking into this! Slang has been of great help for my use case, but sadly this issue has left me unable to upgrade ever since.

**Comment by csyonghe** [comment]
Thank you for reporting the bug. This has been fixed.

Please don't hesitate to report any issues you run into.
